version: 2.1

jobs:
  test:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Configure GitHub credentials
          command: git config --global url."https://${GITHUB_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - run:
          name: Run tests
          command: make test

  publish-dockers:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Setup Buildx
          command: |
            docker buildx create --name multiplatform --driver docker-container --bootstrap --use
      - run:
          name: Publish Model Docker
          command: |
            projectVersion=$(./scripts/git-version.sh)
            echo "$FERNAPI_DOCKER_HUB_PASSWORD" | docker login --username fernapi --password-stdin
            docker buildx build --platform linux/amd64,linux/arm64 -f ./docker/Dockerfile.model -t fernapi/fern-go-model:${projectVersion} --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} . --push
      - run:
          name: Publish SDK Docker
          command: |
            projectVersion=$(./scripts/git-version.sh)
            echo "$FERNAPI_DOCKER_HUB_PASSWORD" | docker login --username fernapi --password-stdin
            docker buildx build --platform linux/amd64,linux/arm64 -f ./docker/Dockerfile.sdk -t fernapi/fern-go-sdk:${projectVersion} --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} . --push

workflows:
  build:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
          context:
            - github
      - publish-dockers:
          filters:
            branches:
              only: main
            tags:
              only:
                - /.*/
          requires:
            - test
          context:
            - docker-hub
            - github
