name: postman-collection-api
definition: src
generators:
  - name: fernapi/fern-postman
    version: 0.0.17
    generate:
      enabled: true
      output: ./generated-postman.json
    config:
      api-key: ${POSTMAN_API_KEY}
      workspace-id: ${POSTMAN_WORKSPACE_ID}
  - name: fernapi/fern-typescript
    version: 0.0.144
    generate: true
    config:
      mode: client
