name: check

on: 
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      
      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Format
        run: yarn format:check

      - name: Check dependencies
        run: yarn depcheck

      - name: Compile
        run: yarn compile

      - name: Run tests
        run: | 
          npm install -g fern-api
          yarn test --ci

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff
  
  snapshot-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      
      - name: Install
        run: yarn install

      - name: Install seed
        run: npm install -g @fern-api/seed-cli@0.15.0-rc51

      - name: Test
        run: seed test --workspace openapi --parallel 10

      - name: Ensure no changes to git-tracked files
        run: git --no-pager diff
