name: publish

on:
  release:
    types: [released]
  push:
    branches:
      - main

jobs:
  check:
    uses: ./.github/workflows/check.yml
  publish-express-docker:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install
        run: yarn install

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fernapi
          password: ${{ secrets.FERN_API_DOCKERHUB_PASSWORD }}

      - name: Compile
        run: yarn compile

      - name: Print Version
        run: ./scripts/git-version.sh

      - name: Publish fernapi/fern-typescript-express docker
        run: |
          projectVersion=$(./scripts/git-version.sh)
          yarn workspace @fern-typescript/express-generator-cli dockerTagVersion "$projectVersion"
          docker push fernapi/fern-typescript-express:"$projectVersion"

  publish-browser-sdk-docker:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install
        run: yarn install

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fernapi
          password: ${{ secrets.FERN_API_DOCKERHUB_PASSWORD }}

      - name: Compile
        run: yarn compile

      - name: Print Version
        run: ./scripts/git-version.sh

      - name: Publish fernapi/fern-typescript-browser-sdk docker
        run: |
          projectVersion=$(./scripts/git-version.sh)
          yarn workspace @fern-typescript/sdk-generator-cli dockerTagVersion:browser "$projectVersion"
          docker push fernapi/fern-typescript-browser-sdk:"$projectVersion"

  publish-node-sdk-docker:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install
        run: yarn install

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fernapi
          password: ${{ secrets.FERN_API_DOCKERHUB_PASSWORD }}

      - name: Compile
        run: yarn compile

      - name: Print Version
        run: ./scripts/git-version.sh

      - name: Publish fernapi/fern-typescript-node-sdk docker
        run: |
          projectVersion=$(./scripts/git-version.sh)
          yarn workspace @fern-typescript/sdk-generator-cli dockerTagVersion:node "$projectVersion"
          docker push fernapi/fern-typescript-node-sdk:"$projectVersion"
